export type { PageResponse, ApiResponse } from './common';

export enum NotificationType {
  BOOKING = 'BOOKING',
  PAYMENT = 'PAYMENT',
  PROMOTION = 'PROMOTION',
  SYSTEM = 'SYSTEM',
  REVIEW = 'REVIEW',
  COMPLAINT = 'COMPLAINT',
  OWNER_APPROVAL = 'OWNER_APPROVAL',
  STADIUM_APPROVAL = 'STADIUM_APPROVAL',
  ACCOUNT_LOCK = 'ACCOUNT_LOCK',
  APPEAL = 'APPEAL',
  REPORT = 'REPORT',

  // Customer specific types
  BOOKING_CONFIRMED = 'BOOKING_CONFIRMED',
  BOOKING_CANCELLED = 'BOOKING_CANCELLED',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  REFUND_PROCESSED = 'REFUND_PROCESSED',
  REFUND_EXCEPTION_DECISION = 'REFUND_EXCEPTION_DECISION',
  COMPLAINT_ACKNOWLEDGED = 'COMPLAINT_ACKNOWLEDGED',
  COMPLAINT_OWNER_REPLIED = 'COMPLAINT_OWNER_REPLIED',
  COMPLAINT_RESOLVED = 'COMPLAINT_RESOLVED',
  COMPLAINT_ESCALATED = 'COMPLAINT_ESCALATED',
  REVIEW_REMINDER = 'REVIEW_REMINDER',
  REVIEW_OWNER_RESPONDED = 'REVIEW_OWNER_RESPONDED',
  MATCH_REQUEST_RECEIVED = 'MATCH_REQUEST_RECEIVED',
  MATCH_REQUEST_APPROVED = 'MATCH_REQUEST_APPROVED',
  MATCH_REQUEST_REJECTED = 'MATCH_REQUEST_REJECTED',
  MATCH_CANCELLED = 'MATCH_CANCELLED',
  UPGRADE_APPROVED = 'UPGRADE_APPROVED',
  UPGRADE_REJECTED = 'UPGRADE_REJECTED',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  ACCOUNT_UNLOCKED = 'ACCOUNT_UNLOCKED',
}

export interface NotificationResponse {
  notificationId: number;
  notificationType: NotificationType;
  title: string;
  message: string;
  isRead: boolean;
  createdAt: string;
  relatedResourceId?: string;
}
