-- Add MATCH_REQUEST and other missing notification types to the check constraint
ALTER TABLE notifications DROP CONSTRAINT notifications_notification_type_check;

ALTER TABLE notifications ADD CONSTRAINT notifications_notification_type_check
    CHECK (notification_type IN (
        'BOOKING', 'PAYMENT', 'PROMOTION', 'SYSTEM', 'REVIEW', 'COMPLAINT',
        'OWNER_APPROVAL', 'STADIUM_APPROVAL', 'ACCOUNT_LOCK', 'APPEAL', 'REPORT',
        'BOOKING_CONFIRMED', 'BOOKING_CANCELLED',
        'PAYMENT_RECEIVED', 'PAYMENT_FAILED',
        'REFUND_PROCESSED', 'REFUND_EXCEPTION_DECISION',
        'COMPLAINT_ACKNOWLEDGED', 'COMPLAINT_OWNER_REPLIED', 'COMPLAINT_RESOLVED', 'COMPLAINT_ESCALATED',
        'REVIEW_REMINDER', 'REVIEW_OWNER_RESPONDED',
        'MATCH_REQUEST_RECEIVED', 'MATCH_REQUEST_APPROVED', 'MATCH_REQUEST_REJECTED', 'MATCH_CANCELLED',
        'UPGRADE_APPROVED', 'UPGRADE_REJECTED',
        'ACCOUNT_LOCKED', 'ACCOUNT_UNLOCKED'
    ));
